import { computeWaPoints } from './events'
import type { Achievement, Athlete, Challenge, Result, Sex } from './types'

export const CURRENT_ATHLETE_ID = 'lucia'

let rid = 0
function makeResult(
  athleteId: string,
  sex: Sex,
  eventId: string,
  markValue: number,
  markLabel: string,
  unit: string,
  wind: number | null,
  date: string,
  competition: string,
  status: Result['status'],
  fileUrl: string | null,
  isPB: boolean,
  isSB: boolean,
): Result {
  rid += 1
  return {
    id: `seed-${rid}`,
    athleteId,
    eventId,
    markValue,
    markLabel,
    unit,
    wind,
    date,
    competition,
    status,
    fileUrl,
    waPoints: computeWaPoints(eventId, sex, markValue),
    isPB,
    isSB,
    createdBy: 'seed',
  }
}

export const ATHLETES: Athlete[] = [
  {
    id: 'lucia',
    username: '@lucia_nav',
    fullName: 'Lucia Navarro',
    birthDate: '2005-01-01',
    avatar: '/avatars/lucia.png',
    category: 'U23',
    sex: 'F',
    club: 'CA Sevilla',
    region: 'Andalusia',
    country: 'Spain',
    spikeScore: 842,
    confidence: 78,
    friendIds: ['miguel', 'sara', 'carla', 'diego'],
  },
  {
    id: 'miguel',
    username: '@migue_t',
    fullName: 'Miguel Torres',
    avatar: '/avatars/miguel.png',
    category: 'Senior',
    sex: 'M',
    club: 'FC Barcelona Atletisme',
    region: 'Catalonia',
    country: 'Spain',
    spikeScore: 901,
    confidence: 92,
    friendIds: ['lucia', 'diego'],
  },
  {
    id: 'sara',
    username: '@sara_r',
    fullName: 'Sara Ruiz',
    avatar: '',
    category: 'U23',
    sex: 'F',
    club: 'CA Málaga',
    region: 'Andalusia',
    country: 'Spain',
    spikeScore: 815,
    confidence: 71,
    friendIds: ['lucia'],
  },
  {
    id: 'carla',
    username: '@carla_m',
    fullName: 'Carla Moreno',
    avatar: '',
    category: 'U23',
    sex: 'F',
    club: 'CA Granada',
    region: 'Andalusia',
    country: 'Spain',
    spikeScore: 788,
    confidence: 64,
    friendIds: ['lucia'],
  },
  {
    id: 'diego',
    username: '@diego_f',
    fullName: 'Diego Fernández',
    avatar: '',
    category: 'Senior',
    sex: 'M',
    club: 'CA Sevilla',
    region: 'Andalusia',
    country: 'Spain',
    spikeScore: 869,
    confidence: 83,
    friendIds: ['lucia', 'miguel'],
  },
  {
    id: 'alejandro',
    username: '@ale_dlc',
    fullName: 'Alejandro Francisco de la Cruz-Morales Jr.',
    avatar: '',
    category: 'Senior',
    sex: 'M',
    club: 'Playas de Castellón',
    region: 'Valencia',
    country: 'Spain',
    spikeScore: 884,
    confidence: 88,
    friendIds: [],
  },
  {
    id: 'elena',
    username: '@elena_v',
    fullName: 'Elena Vidal',
    avatar: '',
    category: 'Senior',
    sex: 'F',
    club: 'Valencia Terra i Mar',
    region: 'Valencia',
    country: 'Spain',
    spikeScore: 856,
    confidence: 90,
    friendIds: [],
  },
  {
    id: 'shelly',
    username: '@shelly_c',
    fullName: 'Shelly Campbell',
    avatar: '',
    category: 'Senior',
    sex: 'F',
    club: 'MVP Track Club',
    region: 'Kingston',
    country: 'Jamaica',
    spikeScore: 978,
    confidence: 96,
    friendIds: [],
  },
  {
    id: 'ama',
    username: '@ama_o',
    fullName: 'Ama Osei',
    avatar: '',
    category: 'Senior',
    sex: 'F',
    club: 'Bytomski AKL',
    region: 'Accra',
    country: 'Ghana',
    spikeScore: 941,
    confidence: 94,
    friendIds: [],
  },
  {
    id: 'noah',
    username: '@noah_w',
    fullName: 'Noah Williams',
    avatar: '',
    category: 'Senior',
    sex: 'M',
    club: 'Nike Union AC',
    region: 'Oregon',
    country: 'USA',
    spikeScore: 1012,
    confidence: 98,
    friendIds: [],
  },
]

export function getAthlete(id: string): Athlete | undefined {
  return ATHLETES.find((a) => a.id === id)
}

export const RESULTS: Result[] = [
  // Lucia — 100m progression (SB + PB, PB pending verification)
  makeResult('lucia', 'F', '100m', 11.78, '11.78', 's', 0.4, '2025-07-18', 'Campeonato Regional', 'approved', 'ra-2025.pdf', false, false),
  makeResult('lucia', 'F', '100m', 11.62, '11.62', 's', -0.6, '2026-04-22', 'Control CA Sevilla', 'approved', 'ctrl-apr.pdf', false, false),
  makeResult('lucia', 'F', '100m', 11.54, '11.54', 's', 1.0, '2026-05-15', 'Meeting Cádiz', 'approved', 'cadiz.pdf', false, false),
  makeResult('lucia', 'F', '100m', 11.45, '11.45', 's', 1.2, '2026-06-12', 'Gran Premio Sevilla', 'approved', 'gp-sevilla.pdf', true, true),
  // Lucia — 200m
  makeResult('lucia', 'F', '200m', 23.9, '23.90', 's', 0.2, '2025-06-30', 'Campeonato Andalucía', 'approved', 'and-2025.pdf', false, false),
  makeResult('lucia', 'F', '200m', 23.71, '23.71', 's', 0.8, '2026-05-15', 'Meeting Cádiz', 'approved', 'cadiz-200.pdf', true, true),
  // Lucia — Long Jump
  makeResult('lucia', 'F', 'LJ', 5.82, '5.82', 'm', 0.5, '2025-05-20', 'Control Indoor', 'approved', 'lj-2025.pdf', false, false),
  makeResult('lucia', 'F', 'LJ', 5.95, '5.95', 'm', 1.1, '2026-04-22', 'Control CA Sevilla', 'approved', 'lj-2026.pdf', true, true),

  // Miguel — 400m
  makeResult('miguel', 'M', '400m', 46.12, '46.12', 's', null, '2026-05-02', 'Meeting Barcelona', 'approved', 'federation.pdf', false, true),
  makeResult('miguel', 'M', '400m', 45.98, '45.98', 's', null, '2025-07-09', 'Campeonato España', 'approved', 'esp-2025.pdf', true, false),

  // Others — primary marks for rankings
  makeResult('sara', 'F', '100m', 11.52, '11.52', 's', 0.9, '2026-06-01', 'Meeting Málaga', 'approved', 'mal.pdf', true, true),
  makeResult('carla', 'F', '100m', 11.71, '11.71', 's', 0.3, '2026-05-28', 'Control Granada', 'quick', null, true, true),
  makeResult('diego', 'M', '100m', 10.62, '10.62', 's', 1.4, '2026-06-05', 'Gran Premio Sevilla', 'approved', 'gp-d.pdf', true, true),
  makeResult('alejandro', 'M', '100m', 10.41, '10.41', 's', 0.7, '2026-05-30', 'Meeting Castellón', 'approved', 'cas.pdf', true, true),
  makeResult('elena', 'F', '100m', 11.33, '11.33', 's', 1.5, '2026-06-08', 'Meeting Valencia', 'approved', 'val.pdf', true, true),
  makeResult('shelly', 'F', '100m', 10.84, '10.84', 's', 0.6, '2026-06-10', 'Racers Grand Prix', 'approved', 'jam.pdf', true, true),
  makeResult('ama', 'F', '100m', 10.98, '10.98', 's', 1.1, '2026-06-09', 'African Champs', 'approved', 'afr.pdf', true, true),
  makeResult('noah', 'M', '100m', 9.94, '9.94', 's', 0.9, '2026-06-11', 'Prefontaine Classic', 'approved', 'pre.pdf', true, true),
  makeResult('miguel', 'M', '100m', 10.71, '10.71', 's', 0.2, '2026-05-20', 'Control Barcelona', 'approved', 'bcn.pdf', false, true),
]

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-11s',
    title: 'First Sub-11.5',
    description: 'Break the 11.50 barrier in the 100m.',
    requirement: 'Record a legal 100m mark under 11.50s.',
    rarity: 'Rare',
    state: 'unlocked',
    icon: 'zap',
  },
  {
    id: 'season-consistency',
    title: 'Season Consistency',
    description: 'Log results in three consecutive meets.',
    requirement: 'Submit a valid result in 3 meets in a row. (2 / 3)',
    rarity: 'Common',
    state: 'in-progress',
    progress: 66,
    icon: 'flame',
  },
  {
    id: 'verified-first',
    title: 'Officially Verified',
    description: 'Get your first federation-verified mark.',
    requirement: 'Upload a result and have it approved by a federation.',
    rarity: 'Common',
    state: 'unlocked',
    icon: 'badge-check',
  },
  {
    id: 'double-threat',
    title: 'Double Threat',
    description: 'Hold a PB in both a sprint and a jump.',
    requirement: 'Set a PB in a track and a field event in one season.',
    rarity: 'Epic',
    state: 'in-progress',
    progress: 50,
    icon: 'target',
  },
  {
    id: 'first-11s-flat',
    title: 'Eleven Flat',
    description: 'Run the 100m under 11.10s.',
    requirement: 'Record a legal 100m under 11.10s.',
    rarity: 'Epic',
    state: 'locked',
    icon: 'timer',
  },
  {
    id: 'top-10-region',
    title: 'Regional Top 10',
    description: 'Reach the top 10 in Andalusia for any event.',
    requirement: 'Be ranked 10th or better in your region.',
    rarity: 'Rare',
    state: 'unlocked',
    icon: 'trophy',
  },
  {
    id: 'national-podium',
    title: 'National Podium',
    description: 'Finish top 3 at a national championship.',
    requirement: 'Place 1st–3rd at a national final.',
    rarity: 'Legendary',
    state: 'locked',
    icon: 'medal',
  },
  {
    id: 'spike-900',
    title: 'SPIKE 900 Club',
    description: 'Push your SPIKE SCORE past 900.',
    requirement: 'Reach a SPIKE SCORE of 900 or higher. (842 / 900)',
    rarity: 'Legendary',
    state: 'in-progress',
    progress: 84,
    icon: 'flame',
  },
]

export const CHALLENGES: Challenge[] = [
  {
    id: 'club-sprint-cup',
    title: 'Sprint Cup',
    type: 'league',
    description: 'Season-long points league for sprinters.',
    participants: 8,
    status: 'active',
    progress: 62,
    reward: '+40 SPIKE bonus',
    daysLeft: 12,
  },
  {
    id: 'duel-sara',
    title: 'Duel vs Sara Ruiz',
    type: 'duel',
    description: 'Head-to-head 100m — best legal mark before month end.',
    participants: 2,
    status: 'active',
    progress: 48,
    reward: 'Bragging rights + badge',
    daysLeft: 6,
  },
  {
    id: 'most-improved',
    title: 'Most Improved — June',
    type: 'challenge',
    description: 'Biggest SPIKE SCORE gain this month among friends.',
    participants: 5,
    status: 'active',
    progress: 71,
    reward: 'Most Improved badge',
    daysLeft: 18,
  },
  {
    id: 'andalusia-relay',
    title: 'Andalusia Challenge Series',
    type: 'league',
    description: 'Regional challenge ladder for your next target.',
    participants: 16,
    status: 'upcoming',
    progress: 0,
    reward: 'Series finals spot',
    daysLeft: 30,
  },
]
